### ISSUE TITLE
ValueError: min() arg is an empty sequence in util\image.py when training on coco 2014 and 2017

### ISSUE THREAD

**Issue by alexiskattan** [fizyr/keras-retinanet#126]
The code is setup to train on coco 2017.  It works for a while and then throws the following error.  I saw there was some talk about this and a fix #93 but I still seem to be getting the issue with the latest code.  I also tried it with coco 2014 and am getting the same issue.

Running `keras-resnet@0.0.8` and `keras@2.1.1`.

```
Epoch 1/50
  316/20000 [..............................] - ETA: 2:29:13 - loss: 1.2430 - regression_loss: 0.0065 - classification_loss: 1.2365Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 633, in data_generator_task
    generator_output = next(self._generator)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 206, in __next__
    return self.next()
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 217, in next
    return self.compute_input_output(group)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\utils\image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
ValueError: min() arg is an empty sequence

  317/20000 [..............................] - ETA: 2:29:03 - loss: 1.2427 - regression_loss: 0.0065 - classification_loss: 1.2362Traceback (most recent call last):
  File "examples/train_coco.py", line 113, in <module>
    keras_retinanet.callbacks.coco.CocoEval(val_generator),
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2111, in fit_generator
    generator_output = next(output_generator)
StopIteration
```

**Comment by hgaiser** [comment]
I see the same issue, I'm looking into it.

**Comment by hgaiser** [comment]
Looks like some COCO bounding boxes have a width < 1 or height < 1... OpenCV happily ignored it, but numpy doesnt :p 
https://github.com/fizyr/keras-retinanet/commit/0e255e08b2fa8a6ec1b797c41677a984e27609bd should fix this.

**Comment by alexiskattan** [comment]
Hmmm... just downloaded the latest code.  It gets a further but still throwing an error.


```
Epoch 1/50
 1815/20000 [=>............................] - ETA: 1:50:57 - loss: 0.9782 - regression_loss: 0.0066 - classification_loss: 0.9716Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 633, in data_generator_task
    generator_output = next(self._generator)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 206, in __next__
    return self.next()
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 217, in next
    return self.compute_input_output(group)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\utils\image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
ValueError: min() arg is an empty sequence

 1816/20000 [=>............................] - ETA: 1:50:56 - loss: 0.9782 - regression_loss: 0.0066 - classification_loss: 0.9715Traceback (most recent call last):
  File "examples/train_coco.py", line 113, in <module>
    keras_retinanet.callbacks.coco.CocoEval(val_generator),
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\alexis\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2111, in fit_generator
    generator_output = next(output_generator)
StopIteration
```
