### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Fraskakan** [fizyr/keras-retinanet#1299]
Hi!
First time posting an issue to any repository, hope I'm doing this right.

I'm trying to run the command 
_**python keras_retinanet/bin/train.py csv training/train_label.csv training/classes.csv**_
From the **keras_retinanet** folder

However, I get this error message:

> Traceback (most recent call last):
>   File "keras_retinanet/bin/train.py", line 35, in <module>
>     from .. import layers  # noqa: F401
>   File "keras_retinanet/bin\..\..\keras_retinanet\layers\__init__.py", line 1, in <module>
>     from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
>   File "keras_retinanet/bin\..\..\keras_retinanet\layers\_misc.py", line 19, in <module>
>     from ..utils import anchors as utils_anchors
>   File "keras_retinanet/bin\..\..\keras_retinanet\utils\anchors.py", line 20, in <module>
>     from ..utils.compute_overlap import compute_overlap
> ImportError: DLL load failed: Couldn't find the module

I have seen others use the solution to run the command **_python setup.py build_ext --inplace_** but that is not working for me, I still get the same error.

I'm running this on a windows 10 64bit.

**Comment by PUTTAKUL** [comment]
Hi Fraskakan. I got the same issue. Have you been able to solve it?

**Comment by Fraskakan** [comment]
No i have not.

**Comment by PUTTAKUL** [comment]
Hi Fraskakan, 
FYI
I reinstalled NVIDIA GPU Computing Toolkit v10.0 and it works now. Previously, I installed v10.2 and put cudart64_100.dll, it seems this trick caused me issue.

**Comment by edgecate** [comment]
Hey mate,
I got the same error using Anaconda and a Jupyter Notebook.
I then tried it through Anaconda Prompt and got the following errors:
ModuleNotFoundError: No module named 'progressbar'
I fixed this with: conda install -c conda-forge progressbar2

Then I got:
ModuleNotFoundError: No module named 'keras_resnet'
I fixed this by running this command inside Anaconda Prompt (didn't work in Jupyter): pip install .

Hope this helps!

**Comment by JinLuckyboy** [comment]
I solved it.

![python retinanet](https://user-images.githubusercontent.com/34185570/80971249-6bcb3580-8e57-11ea-991a-c8c0b8ba7202.png)

It seems to find '/keras_retinanet/utils/compute_overlap.*.pyd' in many directory including $PATH.

Anyway, I added 'keras-retinanet-master/keras_retinanet/utils/keras_retinanet/utils/compute_overlap.*.pyd', and It is solved.

Strange.

**Comment by PhSchuetz** [comment]
Hi guys, I'm having the same issue. 

While `python setup.py build_ext --inplace` did create the **compute_overlap.cp37-win_amd64.pyd** and **compute_overlap.c**  files, I still get the error   
`Traceback (most recent call last):
  File "keras-retinanet/keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\layers\__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\layers\_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\utils\anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ImportError: DLL load failed:`

I'm running on Windows 10, 64 bit. I do not have a GPU, could this cause the problem?

@JinLuckyboy: I tried your suggestion, although I do not completely understand it. I only found the folders `C:\Users\Philipp\anaconda3\Library\bin`, but copying the .pyd file there did not change anything. :(

**Comment by JinLuckyboy** [comment]
@PhSchuetz 
When I tried again, it works without this issue.(can't reappear)

`python setup.py install`
Just try it.

[ First Way ]
Try to find `compute_overlap.*.pyd` in
`C:\ProgramData\Anaconda3\Lib\site-packages\keras_retinanet-*.egg\keras_retinanet\utils`
or
`C:\ProgramData\Anaconda3\envs\{envName}\Lib\site-packages\keras_retinanet-*.egg\keras_retinanet\utils`
If you don't find it, copy it into that.

[ Second Way ]
Install **Process Monitor** (portable).

![image](https://user-images.githubusercontent.com/34185570/81559414-5069a880-93ca-11ea-8c70-e30db601a605.png)
Click Filter.

![image](https://user-images.githubusercontent.com/34185570/81559502-7d1dc000-93ca-11ea-8903-072eee137a3e.png)
![image](https://user-images.githubusercontent.com/34185570/81559510-8149dd80-93ca-11ea-8458-0968bcf6a7d1.png)
Add conditions.
Click OK.

Make `DLL load failed`.

You can find `compute_overlap.*.pyd` in Path, Result of which is PATH NOT FOUND.

Now, you can notice where is load `compute_overlap.*.pyd` in.
