### ISSUE TITLE
Issue loading model

### ISSUE THREAD

**Issue by zrachlin** [fizyr/keras-retinanet#86]
I get the following error when I try to load a model that I trained with train_csv.py:
>>> model = load_model('snapshots/resnet50_csv_final.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1253, in from_config
    return cls(**config)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/layers/normalization.py", line 71, in __init__
    super(BatchNormalization, self).__init__(**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 280, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'freeze')

**Comment by hgaiser** [comment]
You need to pass the custom objects to the `load_model` command.

I added instructions in the [`README.md`](https://github.com/fizyr/keras-retinanet/blob/master/README.md#testing)

**Comment by zrachlin** [comment]
That did it, thanks!

**Comment by reactivetype** [comment]
@hgaiser  What version of Keras should we use for this repo? I am facing this same issue even after passing custom_objects parameters. I am using keras 2.2.0

**Comment by hgaiser** [comment]
I have been using 2.2.4 for a long time now, I haven't tried 2.2.5. 2.2.0 might have some issues that were resolved later on. My advice for now, use 2.2.4.

**Comment by reactivetype** [comment]
Thank you for replying. I still fail when loading a model with mobilenet backbone with error 
`TypeError: ('Keyword argument not understood:', 'freeze')`. It has something to do with batchnorm layer. What custom_objects should I pass when loading mobilenet?
